CREATE TABLE `STUDENT`(
	`STUDENT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(128) DEFAULT NULL,
	`AGE` TINYINT(6),
	PRIMARY KEY (`STUDENT_ID`)
)ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;